### ISSUE TITLE
How do add two augmentations of same type but different probabilities?

### ISSUE THREAD

**Issue by hummuscience** [paninski-lab/lightning-pose#277]
I finally got to try out the new custom augmentation pipeline option. I am trying to re-create the DLC augmentation (including the scaling). This involves doing an Affine scaling (between 0.5 and 1) in all the images. 

I tried the following:

```
  imgaug:                                                                                                           
    Affine:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        scale: [0.5, 1.5]                                                                                           
    Fliplr:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Flipud:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Affine:                                                                                                         
      p: 0.4                                                                                                        
      kwargs:                                                                                                       
        rotate: [-25, 25]        
```     

But that doesnt work as there is a duplicate key.

I also tried the following, that also didnt work 

```
  imgaug:                                                                                                           
    Fliplr:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Flipud:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Affine:                                                                                                         
      p: 0.4                                                                                                        
      kwargs:                                                                                                       
        rotate: [-25, 25]                                                                                           
        scale: [0.5, 1.5]    
```

I ended up doing the following which uses the Rotate augmentation (which is a wrapper around Affine rotate) and that worked:

```
 imgaug:                                                                                                           
    Affine:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        scale: [0.5, 1.5]                                                                                           
    Fliplr:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Flipud:                                                                                                         
      p: 1                                                                                                          
      kwargs:                                                                                                       
        p: 0.5                                                                                                      
    Rotate:                                                                                                         
      p: 0.4                                                                                                        
      kwargs:                                                                                                       
        rotate: [-25, 25]   
```   

But I wonder if this will be an issue in other cases
